services:

  quexf:
    image: acspri/quexf:1.22.0
    ports:
      - 8081:80
    environment:
      QUEXF_DB_USER: root
      QUEXF_DB_PASSWORD: example
      QUEXF_ADMIN_PASSWORD: password
      QUEXF_HTPASSWD_PATH: /opt/quexf/password
      QUEXF_HTGROUP_PATH: /opt/quexf/group
      QUEXF_MULTIPLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_MULTIPLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_SINGLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_SINGLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_HORI_WIDTH_BOX: 56
      QUEXF_VERT_WIDTH_BOX: 56
      QUEXF_BARCODE_TLX_PORTION: 0.5
      QUEXF_BARCODE_TLY_PORTION: 0
      QUEXF_BARCODE_BRX_PORTION: 1
      QUEXF_BARCODE_BRY_PORTION: 0.15
      QUEXF_OCR_ENABLED: 1
    volumes:
      - ./:/var/www/html

  mysql:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_AUTO_UPGRADE: true
    volumes:
      - ./mysql:/var/lib/mysql
