version: '2'

services:

  quexf:
    image: acspri/quexf:latest
    ports:
      - 8081:80
    environment:
      QUEXF_DB_PASSWORD: example
      QUEXF_ADMIN_PASSWORD: password
      QUEXF_OCR_ENABLED: 1
      QUEXF_HORI_WIDTH_BOX: 75
      QUEXF_VERT_WIDTH_BOX: 75
      QUEXF_BARCODE_TLX_PORTION: 0.75
      QUEXF_BARCODE_TLY_PORTION: 0
      QUEXF_BARCODE_BRX_PORTION: 1
      QUEXF_BARCODE_BRY_PORTION: 0.1
      QUEXF_BARCODE_TLX_PORTION2: 0
      QUEXF_BARCODE_TLY_PORTION2: 0.9
      QUEXF_BARCODE_BRX_PORTION2: 0.25
      QUEXF_BARCODE_BRY_PORTION2: 1
      QUEXF_HTPASSWD_PATH: /opt/quexf/password
      QUEXF_HTGROUP_PATH: /opt/quexf/group
      QUEXF_SINGLE_CHOICE_MIN_FILLED: 0.75
      QUEXF_SINGLE_CHOICE_MAX_FILLED: 0.40
      QUEXF_MULTIPLE_CHOICE_MIN_FILLED: 0.75
      QUEXF_MULTIPLE_CHOICE_MAX_FILLED: 0.40

    volumes:
      - ./:/var/www/html



  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
